bm_0:
  access_size: 256
  total_memory_range: 10737418240
  number_operations: 3000
  exec_mode: sequential
  number_threads: 2

bm_1:
  access_size: 512
  number_operations: 3000
  exec_mode: random
  pause_frequency: 0

bm_seq_read:
