bm_0:
  matrix:
    number_threads: [1, 2]
  args:
    access_size: 256
    total_memory_range: 10737418240  // 10 GiB
    number_operations: 10000000
    exec_mode: sequential

bm_1:
  args:
    access_size: 512
    number_operations: 3000
    exec_mode: random
    pause_frequency: 0
