# Ref. Alexander BÃ¶hm: writing of big blocks
intermediate_result:
  matrix:
    number_threads: [ 1, 2, 4, 8, 16, 32 ]
    total_memory_range: [ 10737418240, 1073741824, 104857600 ]  # [10 GiB, 1 GiB, 100 MiB]
    persist_instruction: [ ntstore, none ]

  args:
    exec_mode: random
    access_size: 64
    read_ratio: 0
    write_ratio: 1
