name: CMake Build + Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        build-type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Download Dependencies
      # Install PMDK's dependencies
      run: |
       sudo apt-get update
       sudo apt-get install -y autoconf automake pkg-config libglib2.0-dev libfabric-dev pandoc libncurses5-dev libndctl-dev libdaxctl-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.build-type }}

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build-${{ matrix.build-type }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_PMDK=ON -DBUILD_TEST=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: cmake --build . --config ${{ matrix.build-type }} -- -j

    - name: Test
      working-directory: ${{runner.workspace}}/build-${{ matrix.build-type }}
      shell: bash
      run: ctest -R perma-test -V
